### ISSUE TITLE
iOS 8 - Presenting IBActionSheet from landscape mode causes window to be half the screen

### ISSUE THREAD

**Issue by PhillipApps** [ianb821/IBActionSheet#21]
I was successfully using this amazing framework until iOS 8 came out. Presenting the actionSheet while in landscape mode causes the actionSheet to be offscreen and the background to be cut in half.

So, half window contains the background, half the view.

**Comment by silvaricPresent** [comment]
To exceed that bug I call *rotateToCurrentOrientation* after * showInView*
But I have another problem... When the actionSheet is dismissing, the animation (disappearing flow) is acting like Portrait, in other words, the actionSheet is going down to the left instead of continuing in the center

**Comment by ianb821** [comment]
This should be resolved now with the latest PR.
