### ISSUE TITLE
Control height?

### ISSUE THREAD

**Issue by troypayne** [ianb821/IBActionSheet#27]
I want the height of my buttons (other than Cancel) (I don't have a title) to be 80. Any guidance? Playing with the numbers isn't quite working as I expected

**Comment by ianb821** [comment]
To adjust the height of the button, there would be a few places you'd need to make adjustments.  First you can change the height of the buttons themselves in the `init` method for `IBActionSheetButton`.  Then I believe you would need to change references to the button height in `- (void)setUpTheActionSheet`.  I'm not at a computer and able to test this at the moment, but I believe that should get you started in the right direction.
