### ISSUE TITLE
Project build

### ISSUE THREAD

**Issue by kartikthapar** [ianb821/IBActionSheet#28]
Can you please fix the project build as it fails to build on my machine?

**Comment by ianb821** [comment]
What error are you running into exactly?  What version of iOS are you targeting and what version of Xcode are you using?

**Comment by kartikthapar** [comment]
Error: (null): could not read data from '/Users/kartikthapar/WorkCenter/Projects/IBActionSheet/IBActionSheetSample/IBActionSheetSampleTests/IBActionSheetSampleTests-Info.plist': The file “IBActionSheetSampleTests-Info.plist” couldn’t be opened because there is no such file.

Primarily, some of the source code files seem missing.

Deployment Target is: 8.0/8.1

Xcode version: Version 6.1.1 (6A2008a)

**Comment by ianb821** [comment]
The newest changes should fix the issue you're having.

**Comment by kartikthapar** [comment]
Thanks!
