### ISSUE TITLE
didDismissWithButtonIndex ?

### ISSUE THREAD

**Issue by Jules2010** [ianb821/IBActionSheet#29]
It would be awesome if IBActionSheet supported didDismissWithButtonIndex, clickedButtonAtIndex produces an event too soon for me.

**Comment by ianb821** [comment]
Thanks for the suggestion, I will look into adding the following to IBActionSheet when time permits:

```
- (void)actionSheet:(IBActionSheet *)actionSheet willDismissWithButtonIndex:(NSInteger)buttonIndex;
- (void)actionSheet:(IBActionSheet *)actionSheet didDismissWithButtonIndex:(NSInteger)buttonIndex;
```

**Comment by robtimp** [comment]
@Jules2010 @ianb821 Just opened up a PR for this.

**Comment by ianb821** [comment]
This has been added via a PR from @robtimp.
