### ISSUE TITLE
29 duplicate symbols for architecture i386

### ISSUE THREAD

**Issue by arbnori45** [ianb821/IBActionSheet#31]
Hello, how to fix this problem please tell me. i can't run ibactionsheet, because is shown this error. 
here you have all errors in a note: 
http://justpaste.it/kxad

**Comment by ianb821** [comment]
Your errors refer to [`JGActionSheet`](https://github.com/JonasGessner/JGActionSheet) which I'm not familiar with.  If you are having issue with it I would recommend talking to the developer of it.
