### ISSUE TITLE
Support for accessory icon in buttons

### ISSUE THREAD

**Issue by BigSauce** [ianb821/IBActionSheet#34]
I would love it if IBActionSheetButton support icon functionality similar to [PPiAwesomeButton](https://github.com/pepibumur/PPiAwesomeButton), where an accessory icon can be specified for the button.

Any chance this can happen?

Thanks!

**Comment by ianb821** [comment]
This is outside of the original scope of what I had in mind for the project.  It looks nice though.  Feel free to fork IBActionSheet and add support though, you're free to add whatever you'd like.
