### ISSUE TITLE
How to get "cancelButtonIndex" like in UIActionSheet ?

### ISSUE THREAD

**Issue by Nubaslon** [ianb821/IBActionSheet#38]
Hi!

How i can get actionSheet.cancelButtonIndex?

**Comment by ianb821** [comment]
There is a method `- (NSInteger)cancelButtonIndex` that will give you that information.

**Comment by Nubaslon** [comment]
This method doesn't work, and doesn't finded

**Comment by ianb821** [comment]
Can you show me the code your using, the expected output of `- (NSInteger)cancelButtonIndex`, and the actual output?

**Comment by Nubaslon** [comment]
http://joxi.ru/ZrJO0O0C4ak5mj

**Comment by robtimp** [comment]
@ianb821 I think the issue is that the podspec hasn't been updated, so cancelButtonIndex isn't yet available when installing from the Pod.

**Comment by ianb821** [comment]
Looks like you're right, @robtimp. I updated the podspec so updating your local copy of the pod should take care of the issue for you.
